export const currentDateStr = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }).toUpperCase();

export const newsArticles = [
  { id: 'world1', category: 'WORLD', date: `${currentDateStr}, 2:14 PM`, title: 'Escalating Tensions in Middle East After New Round of Strikes', excerpt: 'Fresh airstrikes have intensified the conflict, drawing international calls for restraint as civilian casualties rise across the region.', source: 'Reuters', cred: 'HIGH CREDIBILITY', credClass: 'cred-high', link: '/investigate/example1', isMain: true, imageUrl: 'https://images.openai.com/static-rsc-4/yfR8vPBESFSSsvbi4mJU8PpZgnAh1CdFgAaDsyiK0VYy768KbX4OoQP-w-0xufTt6Q6uhwalI-yd6Nfwyl5EAtSar0qSaDhDJkiiVWCKGyXaK0VJCvLW280Pyowk7T0kAGbhD-vsoJ2yvJp6pEH1956xStkPz5N2zYjMu5ZE__LOaJTBU9aotfXFMMYuknFy?purpose=fullsize' },
  { id: 'pol1', category: 'POLITICS', date: `${currentDateStr}, 11:32 AM`, title: 'One Explosion. Four Reports. What Actually Happened?', excerpt: 'Different sources claim vastly different casualty numbers in the border region.', source: 'BBC', cred: 'HIGH CREDIBILITY', credClass: 'cred-high', link: '/investigate/example2' },
  { id: 'ind1', category: 'INDIA', date: `${currentDateStr}, 9:40 AM`, title: 'The Number Changed Three Times. Here\'s Where It Started.', excerpt: 'Tracking the source of the widely misreported economic growth figure.', source: 'The Hindu', cred: 'HIGH CREDIBILITY', credClass: 'cred-high', link: '/investigate/example3' },
  { id: 'tech1', category: 'TECH', date: `${currentDateStr}, 10:18 AM`, title: 'Same Speech. Three Headlines. What Each Left Out.', excerpt: 'How different publications framed the CEO\'s senate testimony on AI regulation.', source: 'The Verge', cred: 'MEDIUM', credClass: 'cred-medium', link: '/investigate/example4' },
  { id: 'env1', category: 'ENVIRONMENT', date: `${currentDateStr}, 8:15 AM`, title: 'Global Climate Summit Stalls Over $100B Financing Pledge', excerpt: 'Developing nations walk out of talks demanding immediate monetary commitments.', source: 'Al Jazeera', cred: 'MEDIUM', credClass: 'cred-medium', link: '/investigate/example5' },
  { id: 'econ1', category: 'ECONOMY', date: `${currentDateStr}, 7:30 AM`, title: 'Markets Rally as Inflation Cools to 3.2% in August', excerpt: 'The S&P 500 jumps 400 points as the latest CPI report beats economist predictions.', source: 'Bloomberg', cred: 'HIGH CREDIBILITY', credClass: 'cred-high', link: '/investigate/example6' },
  { id: 'health1', category: 'HEALTH', date: `${currentDateStr}, 6:45 AM`, title: 'FDA Approves First New Alzheimer’s Drug in 20 Years', excerpt: 'Clinical trials show a 27% reduction in cognitive decline over 18 months.', source: 'The Lancet', cred: 'HIGH CREDIBILITY', credClass: 'cred-high', link: '/investigate/example7' },
  { id: 'sports1', category: 'SPORTS', date: `${currentDateStr}, 5:20 AM`, title: 'Manchester City Stripped of Title After Financial Breaches', excerpt: 'Premier League issues historic 115-point deduction following a four-year investigation.', source: 'ESPN', cred: 'MEDIUM', credClass: 'cred-medium', link: '/investigate/example8' },
];
